Reproduce SPR-8639 failure in anticipation of fix
This change re-introduces ProxyFactoryBean usage to demonstrate the
issue described in the previous commit.  Notice that debug logging is
enabled.  The following log statement documents 'ignoring' (suppressing)
the underlying exception.

To fix this issue, we'll see about allowing this exception to propagate
when dealing with ProxyFactoryBeans that do not have a fixed object type
that can be determined by static generics analysis or a call to
getObjectType on an early FactoryBean reference.

DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory
- Ignoring bean creation exception on FactoryBean type check:
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'b' defined in class path resource
[org/springframework/issues/ReproTests-context.xml]: Cannot create inner
bean 'org.springframework.issues.B#7e9ffe3f' of type
[org.springframework.issues.B] while setting bean property 'target';
nested exception is org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'org.springframework.issues.B#7e9ffe3f'
defined in class path resource
[org/springframework/issues/ReproTests-context.xml]: Cannot resolve
reference to bean 'c' while setting bean property 'c'; nested exception
is org.springframework.beans.factory.BeanCurrentlyInCreationException:
Error creating bean with name 'c':
org.springframework.beans.factory.FactoryBeanNotInitializedException:
Cannot determine target class for proxy

Issue: SPR-8639