Add repro case (and workaround) for SPR-6428
Successfully reproduces reported error:

    java.io.FileNotFoundException: class path resource
    [${resourceDirPlaceHolder}/props.properties] cannot be opened
    because it does not exist

And provides a workaround @Test that demonstrates using a
PropertySource to avoid the lifecycle issue that causes the exception
above.

Issue: SPR-6428